apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: operations-cert-manager
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: 'v1.12.3'
    helm:
      releaseName: cert-manager
      values: |
        installCRDs: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: operations-cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
