apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: operations-external-secrets
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: '0.9.2'
    helm:
      releaseName: external-secrets
      values: |
        replicaCount: 2
        nodeSelector:
          kubernetes.io/os: linux
        certController:
          nodeSelector:
            kubernetes.io/os: linux
        webhook:
          nodeSelector:
            kubernetes.io/os: linux
        config:
          webhookAnnotations:
            admissions.enforcer/disabled: "true"
  destination:
    server: https://kubernetes.default.svc
    namespace: operations-external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
