apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: operations-ingress-controller
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: '4.8.3'
    helm:
      releaseName: nginx-ingress-controller
  destination:
    server: https://kubernetes.default.svc
    namespace: operations-ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
