apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: operations-keda
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: keda
    repoURL: https://kedacore.github.io/charts
    targetRevision: '2.11.2'
    helm:
      releaseName: keda
      values: |
        operator:
          replicaCount: 1
        webhooks:
          replicaCount: 1
        nodeSelector:
          kubernetes.io/os: linux
  destination:
    server: https://kubernetes.default.svc
    namespace: operations-keda
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
